<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>LTAI.Agent.Eia</RootNamespace>
    <DefineConstants>$(DefineConstants);HAVE_EIA</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LTAI.Agent\LTAI.Agent.csproj" />
    <ProjectReference Include="..\LTAI.AI\LTAI.AI.csproj" />
  </ItemGroup>

</Project>
