<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>LTAI.Mm</AssemblyName>
    <RootNamespace>LTAI.Mm</RootNamespace>
    <IsAotCompatible>true</IsAotCompatible>
    <NoWarn>$(NoWarn);IL2075</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LTAI.Core\LTAI.Core.csproj" />
  </ItemGroup>

</Project>
