<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.Extensions.AI" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" VersionOverride="17.14.1" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Spectre.Console.Testing" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Terminal.Gui" HintPath="..\..\dist\lib\terminal.gui\Terminal.Gui.dll" Condition="Exists('..\..\dist\lib\terminal.gui\Terminal.Gui.dll')" />
    <Reference Include="Terminal.Gui.Editor" HintPath="..\..\dist\lib\editor\Terminal.Gui.Editor.dll" Condition="Exists('..\..\dist\lib\editor\Terminal.Gui.Editor.dll')" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\LTAI.TUI\LTAI.TUI.csproj" />
  </ItemGroup>

</Project>