using System.Collections.Concurrent;
using System.Text.RegularExpressions;
using LTAI.Execution.Models;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;

namespace LTAI.Execution.Session;

public sealed class GlobalRulePool
{
    public const int POOL_MAX_RULES = 500;
    public const int MAX_PER_NAMESPACE = 100;

    private static readonly List<CompressionRule> TACO_SEED_RULES = new()
    {
        new CompressionRule
        {
            Id = "git_diff_shortstat", Name = "Git Diff Shortstat", Namespace = "git",
            Priority = 100, Action = RuleAction.TruncateTail,
            MatchPattern = @"\d+ files? changed", TruncateLines = 5,
            CreatedAt = DateTime.UtcNow, AutoGenerated = true
        },
        new CompressionRule
        {
            Id = "git_log_truncate", Name = "Git Log Truncate", Namespace = "git",
            Priority = 90, Action = RuleAction.TruncateTail,
            MatchPattern = @"commit\s+[a-f0-9]+", TruncateLines = 3,
            CreatedAt = DateTime.UtcNow, AutoGenerated = true
        },
        new CompressionRule
        {
            Id = "git_status_summary", Name = "Git Status Summary", Namespace = "git",
            Priority = 80, Action = RuleAction.ExtractPattern,
            MatchContext = @"branch|modified|untracked",
            CreatedAt = DateTime.UtcNow, AutoGenerated = true
        },
        new CompressionRule
        {
            Id = "build_errors_only", Name = "Build Errors Only", Namespace = "build",
            Priority = 100, Action = RuleAction.ExtractPattern,
            ExtractRegex = @"error\s+\w+.*|Error\s+\w+.*",
            CreatedAt = DateTime.UtcNow, AutoGenerated = true
        },
        new CompressionRule
        {
            Id = "build_warnings_condense", Name = "Build Warnings Condense", Namespace = "build",
            Priority = 80, Action = RuleAction.Condense,
            MatchPattern = @"warning",
            CreatedAt = DateTime.UtcNow, AutoGenerated = true
        },
        new CompressionRule
        {
            Id = "test_summary", Name = "Test Summary", Namespace = "test",
            Priority = 100, Action = RuleAction.ExtractPattern,
            MatchContext = @"passed|failed|skipped",
            ExtractRegex = @"(\d+)\s+passed.*(\d+)\s+failed",
            CreatedAt = DateTime.UtcNow, AutoGenerated = true
        },
        new CompressionRule
        {
            Id = "test_failures_detail", Name = "Test Failures Detail", Namespace = "test",
            Priority = 85, Action = RuleAction.TruncateTail,
            MatchPattern = @"FAILED|FAIL:", TruncateLines = 8,
            CreatedAt = DateTime.UtcNow, AutoGenerated = true
        },
        new CompressionRule
        {
            Id = "stack_trace_compress", Name = "Stack Trace Compress", Namespace = "error",
            Priority = 100, Action = RuleAction.TruncateTail,
            MatchPattern = @"at\s+\S+\(", TruncateLines = 10,
            CreatedAt = DateTime.UtcNow, AutoGenerated = true
        },
        new CompressionRule
        {
            Id = "error_first_last", Name = "Error First Last", Namespace = "error",
            Priority = 90, Action = RuleAction.ExtractPattern,
            ExtractRegex = @"^Error:.*$",
            CreatedAt = DateTime.UtcNow, AutoGenerated = true
        },
        new CompressionRule
        {
            Id = "shell_output_trim", Name = "Shell Output Trim", Namespace = "shell",
            Priority = 70, Action = RuleAction.TruncateTail,
            MatchContext = @"Usage:", TruncateChars = 500,
            CreatedAt = DateTime.UtcNow, AutoGenerated = true
        },
        new CompressionRule
        {
            Id = "npm_audit_summary", Name = "NPM Audit Summary", Namespace = "npm",
            Priority = 100, Action = RuleAction.ExtractPattern,
            ExtractRegex = @"found\s+\d+\s+vulnerabilit",
            CreatedAt = DateTime.UtcNow, AutoGenerated = true
        },
        new CompressionRule
        {
            Id = "npm_install_summary", Name = "NPM Install Summary", Namespace = "npm",
            Priority = 90, Action = RuleAction.TruncateTail,
            MatchPattern = @"added\s+\d+\s+packages?", TruncateLines = 3,
            CreatedAt = DateTime.UtcNow, AutoGenerated = true
        },
        new CompressionRule
        {
            Id = "nuget_restore_trim", Name = "NuGet Restore Trim", Namespace = "nuget",
            Priority = 80, Action = RuleAction.TruncateTail,
            MatchPattern = @"Restored|Installed|dotnet\s+restore", TruncateLines = 3,
            CreatedAt = DateTime.UtcNow, AutoGenerated = true
        },
        new CompressionRule
        {
            Id = "docker_build_summary", Name = "Docker Build Summary", Namespace = "docker",
            Priority = 90, Action = RuleAction.ExtractPattern,
            ExtractRegex = @"Successfully\s+(built|tagged)",
            CreatedAt = DateTime.UtcNow, AutoGenerated = true
        }
    };

    private readonly ConcurrentDictionary<string, CompressionRule> _rules = new();
    private readonly ConcurrentDictionary<string, HashSet<string>> _byNamespace = new();
    private readonly ConcurrentDictionary<string, int> _hitCounts = new();
    private readonly ConcurrentDictionary<string, int> _missCounts = new();
    private readonly ILogger _logger;
    private readonly string? _persistPath;

    private static readonly Lazy<GlobalRulePool> _instance = new(() => new GlobalRulePool());
    public static GlobalRulePool Instance => _instance.Value;

    public GlobalRulePool(ILogger? logger = null, string? persistPath = null)
    {
        _logger = logger ?? NullLogger.Instance;
        _persistPath = persistPath;
        SeedDefaultRules();
    }

    public void Add(CompressionRule rule)
    {
        var ns = string.IsNullOrEmpty(rule.Namespace) ? "general" : rule.Namespace;
        rule.Namespace = ns;

        var id = rule.Id;
        if (string.IsNullOrEmpty(id))
        {
            id = $"{ns}_{Guid.NewGuid():N}";
            rule.Id = id;
        }
        else if (_rules.ContainsKey(id))
        {
            id = $"{ns}_{id}";
            rule.Id = id;
        }

        _byNamespace.AddOrUpdate(
            ns,
            _ => new HashSet<string> { id },
            (_, set) =>
            {
                lock (set)
                {
                    if (set.Count >= MAX_PER_NAMESPACE)
                    {
                        PruneOldestInSet(set, 1);
                    }
                    set.Add(id);
                }
                return set;
            });

        if (_rules.Count >= POOL_MAX_RULES)
        {
            PruneOldestOverall(1);
        }

        _rules.TryAdd(id, rule);
    }

    public List<CompressionRule> Query(string? namespace_ = null, RuleAction? action = null, int minPriority = 0)
    {
        IEnumerable<CompressionRule> query = _rules.Values;

        if (!string.IsNullOrEmpty(namespace_))
        {
            query = query.Where(r =>
                string.Equals(r.Namespace, namespace_, StringComparison.OrdinalIgnoreCase));
        }

        if (action.HasValue)
        {
            query = query.Where(r => r.Action == action.Value);
        }

        if (minPriority > 0)
        {
            query = query.Where(r => r.Priority >= minPriority);
        }

        return query.OrderByDescending(r => r.Priority).ToList();
    }

    public List<CompressionRule> GetRulesForNamespace(string namespace_)
    {
        var results = new List<CompressionRule>();

        if (_byNamespace.TryGetValue(namespace_, out var nsIds))
        {
            lock (nsIds)
            {
                foreach (var id in nsIds)
                {
                    if (_rules.TryGetValue(id, out var rule))
                        results.Add(rule);
                }
            }
        }

        if (namespace_ != "general" && _byNamespace.TryGetValue("general", out var generalIds))
        {
            lock (generalIds)
            {
                foreach (var id in generalIds)
                {
                    if (_rules.TryGetValue(id, out var rule))
                        results.Add(rule);
                }
            }
        }

        return results.OrderByDescending(r => r.Priority).ToList();
    }

    public List<CompressionRule> FindMatching(string text, string namespace_, string? context = null)
    {
        var candidates = GetRulesForNamespace(namespace_);
        var matching = new List<CompressionRule>();

        foreach (var rule in candidates)
        {
            if (string.IsNullOrEmpty(rule.MatchPattern) && string.IsNullOrEmpty(rule.MatchContext))
                continue;

            var textMatches = true;
            var contextMatches = true;

            if (!string.IsNullOrEmpty(rule.MatchPattern))
            {
                try
                {
                    textMatches = Regex.IsMatch(text, rule.MatchPattern, RegexOptions.Multiline);
                }
                catch (RegexParseException ex)
                {
                    _logger.LogWarning(ex, "Invalid MatchPattern regex for rule {RuleId}", rule.Id);
                    textMatches = false;
                }
            }

            if (!string.IsNullOrEmpty(rule.MatchContext) && context != null)
            {
                try
                {
                    contextMatches = Regex.IsMatch(context, rule.MatchContext, RegexOptions.IgnoreCase);
                }
                catch (RegexParseException ex)
                {
                    _logger.LogWarning(ex, "Invalid MatchContext regex for rule {RuleId}", rule.Id);
                    contextMatches = false;
                }
            }

            if (textMatches && contextMatches)
            {
                matching.Add(rule);
            }
        }

        return matching.OrderByDescending(r => r.Priority).ToList();
    }

    public string ApplyRule(CompressionRule rule, string text)
    {
        return rule.Action switch
        {
            RuleAction.TruncateTail => ApplyTruncateTail(rule, text),
            RuleAction.ExtractPattern => ApplyExtractPattern(rule, text),
            RuleAction.Remove => ApplyRemove(rule, text),
            RuleAction.Replace => ApplyReplace(rule, text),
            RuleAction.Condense => ApplyCondense(text),
            RuleAction.PassThrough => text,
            _ => text
        };
    }

    public string ApplyAllMatching(List<CompressionRule> rules, string text)
    {
        var current = text;
        foreach (var rule in rules.OrderByDescending(r => r.Priority))
        {
            try
            {
                current = ApplyRule(rule, current);
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Rule {RuleId} failed during ApplyAllMatching", rule.Id);
            }
        }
        return current;
    }

    public void SeedDefaultRules()
    {
        foreach (var rule in TACO_SEED_RULES)
        {
            var clone = new CompressionRule
            {
                Id = rule.Id,
                Name = rule.Name,
                Namespace = rule.Namespace,
                Priority = rule.Priority,
                Action = rule.Action,
                MatchPattern = rule.MatchPattern,
                MatchContext = rule.MatchContext,
                TruncateLines = rule.TruncateLines,
                TruncateChars = rule.TruncateChars,
                ExtractRegex = rule.ExtractRegex,
                ReplacePattern = rule.ReplacePattern,
                ReplaceWith = rule.ReplaceWith,
                CreatedAt = DateTime.UtcNow,
                AutoGenerated = true
            };

            if (!_rules.ContainsKey(clone.Id))
            {
                var ns = clone.Namespace;
                _byNamespace.AddOrUpdate(
                    ns,
                    _ => new HashSet<string> { clone.Id },
                    (_, set) =>
                    {
                        lock (set) set.Add(clone.Id);
                        return set;
                    });
                _rules.TryAdd(clone.Id, clone);
            }
        }
    }

    public void RecordHit(string ruleId)
    {
        _hitCounts.AddOrUpdate(ruleId, 1, (_, c) => c + 1);

        if (_rules.TryGetValue(ruleId, out var rule))
        {
            rule.HitCount++;
            rule.LastHit = DateTime.UtcNow;
        }
    }

    public void RecordMiss(string ruleId)
    {
        _missCounts.AddOrUpdate(ruleId, 1, (_, c) => c + 1);

        if (_rules.TryGetValue(ruleId, out var rule))
        {
            rule.FalsePositiveCount++;
        }
    }

    public void PruneExpired()
    {
        var now = DateTime.UtcNow;
        var expiredIds = new List<string>();

        foreach (var (id, rule) in _rules)
        {
            if (rule.ExpiresAt.HasValue && rule.ExpiresAt.Value < now)
            {
                expiredIds.Add(id);
            }
        }

        foreach (var id in expiredIds)
        {
            if (_rules.TryRemove(id, out var removedRule))
            {
                var ns = removedRule.Namespace;
                if (_byNamespace.TryGetValue(ns, out var set))
                {
                    lock (set) set.Remove(id);
                    if (set.Count == 0)
                    {
                        _byNamespace.TryRemove(ns, out _);
                    }
                }
                _hitCounts.TryRemove(id, out _);
                _missCounts.TryRemove(id, out _);
            }
        }
    }

    public Dictionary<string, object?> GetStats()
    {
        int totalRules = _rules.Count;
        var perNamespace = new Dictionary<string, int>();
        double totalPriority = 0;

        foreach (var (ns, ids) in _byNamespace)
        {
            lock (ids)
            {
                perNamespace[ns] = ids.Count;
            }
        }

        foreach (var rule in _rules.Values)
        {
            totalPriority += rule.Priority;
        }

        double avgPriority = totalRules > 0 ? totalPriority / totalRules : 0;

        return new Dictionary<string, object?>
        {
            ["total_rules"] = totalRules,
            ["namespaces"] = perNamespace.Count,
            ["per_namespace"] = perNamespace,
            ["avg_priority"] = Math.Round(avgPriority, 2),
            ["total_hits"] = _hitCounts.Values.Sum(),
            ["total_misses"] = _missCounts.Values.Sum()
        };
    }

    private void PruneOldestInSet(HashSet<string> set, int count)
    {
        var entries = new List<(string Id, DateTime Timestamp)>();
        foreach (var id in set)
        {
            if (_rules.TryGetValue(id, out var rule))
            {
                var ts = rule.LastHit ?? rule.CreatedAt;
                entries.Add((id, ts));
            }
        }

        foreach (var (id, _) in entries.OrderBy(e => e.Timestamp).Take(count))
        {
            set.Remove(id);
            _rules.TryRemove(id, out _);
            _hitCounts.TryRemove(id, out _);
            _missCounts.TryRemove(id, out _);
        }
    }

    private void PruneOldestOverall(int count)
    {
        var entries = _rules
            .Select(kv => (kv.Key, Timestamp: kv.Value.LastHit ?? kv.Value.CreatedAt))
            .OrderBy(e => e.Timestamp)
            .Take(count)
            .ToList();

        foreach (var (id, _) in entries)
        {
            if (_rules.TryRemove(id, out var removed))
            {
                if (_byNamespace.TryGetValue(removed.Namespace, out var set))
                {
                    lock (set) set.Remove(id);
                    if (set.Count == 0)
                        _byNamespace.TryRemove(removed.Namespace, out _);
                }
                _hitCounts.TryRemove(id, out _);
                _missCounts.TryRemove(id, out _);
            }
        }
    }

    private static string ApplyTruncateTail(CompressionRule rule, string text)
    {
        if (rule.TruncateLines > 0)
        {
            var lines = text.Split('\n');
            if (lines.Length > rule.TruncateLines)
            {
                return string.Join('\n', lines.Take(rule.TruncateLines));
            }
        }

        if (rule.TruncateChars > 0 && text.Length > rule.TruncateChars)
        {
            return text[..rule.TruncateChars];
        }

        return text;
    }

    private static string ApplyExtractPattern(CompressionRule rule, string text)
    {
        if (string.IsNullOrEmpty(rule.ExtractRegex))
            return text;

        try
        {
            var matches = Regex.Matches(text, rule.ExtractRegex, RegexOptions.Multiline);
            if (matches.Count > 0)
            {
                return string.Join('\n', matches.Select(m => m.Value));
            }
        }
        catch (RegexParseException) { /* invalid regex pattern */ }

        return text;
    }

    private static string ApplyRemove(CompressionRule rule, string text)
    {
        if (string.IsNullOrEmpty(rule.MatchPattern))
            return text;

        try
        {
            var result = Regex.Replace(text, rule.MatchPattern, "", RegexOptions.Multiline);
            return Regex.Replace(result, @"\n{3,}", "\n\n");
        }
        catch (RegexParseException) { /* invalid regex pattern */ }

        return text;
    }

    private static string ApplyReplace(CompressionRule rule, string text)
    {
        if (string.IsNullOrEmpty(rule.ReplacePattern) || rule.ReplaceWith == null)
            return text;

        try
        {
            return Regex.Replace(text, rule.ReplacePattern, rule.ReplaceWith, RegexOptions.Multiline);
        }
        catch (RegexParseException) { /* invalid regex pattern */ }

        return text;
    }

    private static string ApplyCondense(string text)
    {
        var condensed = Regex.Replace(text, @"\n{3,}", "\n\n");
        var lines = condensed.Split('\n');
        var seen = new HashSet<string>();
        var deduped = new List<string>();

        foreach (var line in lines)
        {
            var trimmed = line.Trim();
            if (seen.Add(trimmed))
            {
                deduped.Add(line);
            }
        }

        return string.Join('\n', deduped);
    }
}
