using System.Text;
using Spectre.Console;

namespace LTAI.Cli.Commands;

public static class InitCommand
{
    public static async Task<int> RunAsync()
    {
        AnsiConsole.Write(new Rule("[yellow]LTAI Setup Wizard[/]") { Style = Style.Parse("bold yellow") });
        AnsiConsole.MarkupLine("\n[grey]Let's configure your LTAI environment.[/]\n");

        // Step 1: LLM Provider
        var provider = AnsiConsole.Prompt(
            new SelectionPrompt<string>()
                .Title("[bold]Which LLM provider do you want to use?[/]")
                .PageSize(5)
                .AddChoices(["DeepSeek", "OpenAI", "SiliconFlow", "DashScope", "Ollama (local)", "I'll set up manually"]));

        var apiKey = "";
        var model = "";
        var endpoint = "";

        if (provider != "Ollama (local)" && provider != "I'll set up manually")
        {
            apiKey = AnsiConsole.Prompt(
                new TextPrompt<string>($"[bold]Enter your {provider} API Key:[/]")
                    .PromptStyle("grey")
                    .Secret());

            var providerLower = provider.ToLowerInvariant();
            var envKey = providerLower switch
            {
                "deepseek" => "DEEPSEEK_API_KEY",
                "openai" => "OPENAI_API_KEY",
                "siliconflow" => "SILICONFLOW_API_KEY",
                "dashscope" => "DASHSCOPE_API_KEY",
                _ => "LLM_API_KEY"
            };

            Environment.SetEnvironmentVariable(envKey, apiKey);
        }
        else if (provider == "Ollama (local)")
        {
            endpoint = AnsiConsole.Prompt(
                new TextPrompt<string>("[bold]Ollama endpoint:[/]")
                    .DefaultValue("http://localhost:11434")
                    .PromptStyle("grey"));
            model = AnsiConsole.Prompt(
                new TextPrompt<string>("[bold]Model name (e.g. qwen3:8b):[/]")
                    .DefaultValue("qwen3:8b")
                    .PromptStyle("grey"));
        }

        // Step 2: Sandbox mode
        var sandboxMode = AnsiConsole.Prompt(
            new SelectionPrompt<string>()
                .Title("[bold]Sandbox execution mode:[/]")
                .PageSize(3)
                .AddChoices(["Local (no isolation)", "Docker (container per task)", "None (read-only mode)"]));

        // Step 3: Web search
        var enableSearch = AnsiConsole.Confirm("[bold]Enable web search?[/]", false);
        var searchProvider = "";
        var searchApiKey = "";
        if (enableSearch)
        {
            searchProvider = AnsiConsole.Prompt(
                new SelectionPrompt<string>()
                    .Title("[bold]Search provider:[/]")
                    .PageSize(3)
                    .AddChoices(["Tavily", "Bing", "SearXNG (self-hosted)"]));

            if (searchProvider != "SearXNG (self-hosted)")
            {
                searchApiKey = AnsiConsole.Prompt(
                    new TextPrompt<string>($"[bold]{searchProvider} API Key:[/]")
                        .PromptStyle("grey")
                        .Secret());
            }
        }

        // Step 4: Save configuration
        var envPath = Path.Combine(Directory.GetCurrentDirectory(), ".env");
        var sb = new StringBuilder();

        if (File.Exists(envPath))
            sb.AppendLine(await File.ReadAllTextAsync(envPath));

        sb.AppendLine($"# Generated by LTAI Setup Wizard at {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine();

        var providerEnv = provider.ToLowerInvariant() switch
        {
            "deepseek" => "DEEPSEEK",
            "openai" => "OPENAI",
            "siliconflow" => "SILICONFLOW",
            "dashscope" => "DASHSCOPE",
            "ollama (local)" => "OLLAMA",
            _ => "DEFAULT"
        };

        if (!string.IsNullOrEmpty(apiKey))
        {
            var key = provider.ToLowerInvariant() switch
            {
                "deepseek" => "DEEPSEEK_API_KEY",
                "openai" => "OPENAI_API_KEY",
                "siliconflow" => "SILICONFLOW_API_KEY",
                "dashscope" => "DASHSCOPE_API_KEY",
                _ => "LLM_API_KEY"
            };
            sb.AppendLine($"{key}={apiKey}");
        }

        if (provider == "Ollama (local)")
        {
            sb.AppendLine($"LTAI_AI_DEFAULTPROVIDER=ollama");
            if (!string.IsNullOrEmpty(endpoint)) sb.AppendLine($"OLLAMA_ENDPOINT={endpoint}");
            if (!string.IsNullOrEmpty(model)) sb.AppendLine($"OLLAMA_MODEL={model}");
        }
        else if (provider != "I'll set up manually")
        {
            sb.AppendLine($"LTAI_AI_DEFAULTPROVIDER={providerEnv.ToLowerInvariant()}");
        }

        if (enableSearch)
        {
            var searchEnvKey = searchProvider.ToLowerInvariant() switch
            {
                "tavily" => "TAVILY_API_KEY",
                "bing" => "BING_API_KEY",
                _ => ""
            };
            if (!string.IsNullOrEmpty(searchEnvKey) && !string.IsNullOrEmpty(searchApiKey))
                sb.AppendLine($"{searchEnvKey}={searchApiKey}");
        }

        // Sandbox mode
        var sandboxModeVal = sandboxMode switch
        {
            "Docker (container per task)" => "docker",
            "Local (no isolation)" => "local",
            _ => "none"
        };
        sb.AppendLine($"LTAI_SANDBOX_MODE={sandboxModeVal}");

        await File.WriteAllTextAsync(envPath, sb.ToString());
        AnsiConsole.MarkupLine($"\n[green]✓[/] Configuration saved to [bold]{envPath}[/]");

        // Summary
        AnsiConsole.Write(new Rule("[green]Setup Complete[/]") { Style = Style.Parse("bold green") });
        var summary = new Table().Border(TableBorder.Rounded);
        summary.AddColumn("Setting"); summary.AddColumn("Value");
        summary.AddRow("Provider", provider.EscapeMarkup());
        if (!string.IsNullOrEmpty(apiKey)) summary.AddRow("API Key", "***" + apiKey[^4..]);
        summary.AddRow("Sandbox", sandboxMode.EscapeMarkup());
        summary.AddRow("Web Search", enableSearch ? searchProvider.EscapeMarkup() : "Disabled");
        AnsiConsole.Write(summary);

        AnsiConsole.MarkupLine("\n[grey]Run [bold]ltai health[/] to verify your setup.[/]");
        return 0;
    }
}
