using System.Text;
using LTAI.Core.Interfaces;

namespace LTAI.MCP;

public sealed class ToolCodeGenerator
{
    public string GeneratePythonModule(string toolGroup, List<(string Name, string Description, Dictionary<string, string>? Parameters)> tools)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"\"\"\"");
        sb.AppendLine($"{toolGroup}: {tools.Count} tools available");
        sb.AppendLine($"Generated by LTAI ToolCodeGenerator");
        sb.AppendLine($"\"\"\"");
        sb.AppendLine();

        foreach (var (name, desc, parameters) in tools)
        {
            var safeName = SanitizeFunctionName(name);
            var paramList = parameters != null && parameters.Count > 0
                ? string.Join(", ", parameters.Select(p => $"{SanitizePythonName(p.Key)}: str = \"\""))
                : "";

            sb.AppendLine($"def {safeName}({paramList}):");
            sb.AppendLine($"    \"\"\"");
            sb.AppendLine($"    {desc}");
            if (parameters != null)
            {
                foreach (var (k, v) in parameters)
                    sb.AppendLine($"    Args: {SanitizePythonName(k)}: {v}");
            }
            sb.AppendLine($"    \"\"\"");
            sb.AppendLine($"    args = {{}}");
            if (parameters != null)
            {
                foreach (var (k, _) in parameters)
                    sb.AppendLine($"    args[\"{k}\"] = {SanitizePythonName(k)}");
            }
            sb.AppendLine($"    return _call_tool(\"{name}\", args)");
            sb.AppendLine();
        }

        sb.AppendLine("def _call_tool(name, args):");
        sb.AppendLine("    \"\"\"Internal MCP bridge to LTAI tool registry\"\"\"");
        sb.AppendLine("    import json, urllib.request");
        sb.AppendLine("    payload = json.dumps({\"jsonrpc\": \"2.0\", \"id\": 1, \"method\": \"tools/call\",");
        sb.AppendLine("        \"params\": {\"name\": name, \"arguments\": args}})");
        sb.AppendLine("    req = urllib.request.Request(");
        sb.AppendLine("        _MCP_ENDPOINT, data=payload.encode(),");
        sb.AppendLine("        headers={\"Content-Type\": \"application/json\"})");
        sb.AppendLine("    resp = urllib.request.urlopen(req)");
        sb.AppendLine("    result = json.loads(resp.read())");
        sb.AppendLine("    return result.get(\"result\", result)");
        sb.AppendLine();
        sb.AppendLine("_MCP_ENDPOINT = \"http://localhost:8080/mcp\"");

        return sb.ToString();
    }

    public string GenerateImportBlock(List<string> toolGroups)
    {
        var sb = new StringBuilder();
        foreach (var group in toolGroups)
        {
            var modName = SanitizePythonName(group);
            sb.AppendLine($"from tools.{modName} import *");
        }
        return sb.ToString().TrimEnd();
    }

    public string GenerateSandboxHeader(Dictionary<string, string> toolGroups)
    {
        var sb = new StringBuilder();
        sb.AppendLine("\"\"\"");
        sb.AppendLine("LTAI Programmatic Tool Calling - Sandbox");
        sb.AppendLine("Available tool groups:");
        foreach (var (group, desc) in toolGroups)
            sb.AppendLine($"  {group}: {desc}");
        sb.AppendLine();
        sb.AppendLine("Usage pattern:");
        sb.AppendLine("  1. Import tools: from tools.<group> import <function>");
        sb.AppendLine("  2. Process data in sandbox (stays local, zero tokens)");
        sb.AppendLine("  3. Only final results return to the model");
        sb.AppendLine("\"\"\"");
        return sb.ToString();
    }

    public string GenerateProgressiveToolPrompt(List<string> availableGroups, string? currentTask = null)
    {
        var sb = new StringBuilder();
        sb.AppendLine("## Available Tool Groups (PTC - Progressive Tool Calling)");
        sb.AppendLine();
        sb.AppendLine("Instead of making individual JSON tool calls, write Python code that imports and calls tools.");
        sb.AppendLine("This reduces token usage by 85-98% for bulk data operations.");
        sb.AppendLine();
        sb.AppendLine("### Tool Groups Available:");
        foreach (var group in availableGroups)
            sb.AppendLine($"  - {group}");

        if (!string.IsNullOrWhiteSpace(currentTask))
            sb.AppendLine($"\n### Current Task: {currentTask}");

        sb.AppendLine();
        sb.AppendLine("### Pattern:");
        sb.AppendLine("```python");
        sb.AppendLine("from tools.<group> import <function>");
        sb.AppendLine("");
        sb.AppendLine("# Fetch data (stays in sandbox)");
        sb.AppendLine("data = <function>(param=\"value\")");
        sb.AppendLine("");
        sb.AppendLine("# Process locally (no tokens wasted)");
        sb.AppendLine("result = process(data)");
        sb.AppendLine("");
        sb.AppendLine("# Only summary returns to model");
        sb.AppendLine("print(json.dumps({\"summary\": result}))");
        sb.AppendLine("```");

        return sb.ToString();
    }

    private static string SanitizeFunctionName(string name)
    {
        var sb = new StringBuilder();
        foreach (var c in name)
        {
            if (char.IsLetterOrDigit(c) || c == '_')
                sb.Append(c);
            else
                sb.Append('_');
        }
        var result = sb.ToString().Trim('_').ToLowerInvariant();
        if (result.Length == 0 || char.IsDigit(result[0]))
            result = "fn_" + result;
        return result;
    }

    private static string SanitizePythonName(string name)
    {
        var safe = SanitizeFunctionName(name);
        var reserved = new HashSet<string> { "def", "class", "import", "from", "return", "if", "else",
            "for", "while", "try", "except", "with", "as", "in", "is", "not", "and", "or", "lambda",
            "pass", "break", "continue", "yield", "raise", "True", "False", "None" };
        return reserved.Contains(safe) ? safe + "_" : safe;
    }
}
