namespace LTAI.Mm.Core;

public enum MmValueType : byte
{
    Unknown,
    Doc,
    Obj,
    Map,
    Vec,
    Arr,
    Bool,
    I,
    I8,
    I16,
    I32,
    I64,
    U,
    U8,
    U16,
    U32,
    U64,
    BigInt,
    F32,
    F64,
    Decimal,
    Str,
    Bytes,
    DateTime,
    Date,
    Time,
    Uuid,
    Ip,
    Url,
    Email,
    Enums,
    Media,
}

public static class MmValueTypeExtensions
{
    public static string ToTypeString(this MmValueType vt) => vt switch
    {
        MmValueType.Doc => "doc",
        MmValueType.Obj => "obj",
        MmValueType.Map => "map",
        MmValueType.Vec => "vec",
        MmValueType.Arr => "arr",
        MmValueType.Bool => "bool",
        MmValueType.I => "i",
        MmValueType.I8 => "i8",
        MmValueType.I16 => "i16",
        MmValueType.I32 => "i32",
        MmValueType.I64 => "i64",
        MmValueType.U => "u",
        MmValueType.U8 => "u8",
        MmValueType.U16 => "u16",
        MmValueType.U32 => "u32",
        MmValueType.U64 => "u64",
        MmValueType.BigInt => "bigint",
        MmValueType.F32 => "f32",
        MmValueType.F64 => "f64",
        MmValueType.Decimal => "decimal",
        MmValueType.Str => "str",
        MmValueType.Bytes => "bytes",
        MmValueType.DateTime => "datetime",
        MmValueType.Date => "date",
        MmValueType.Time => "time",
        MmValueType.Uuid => "uuid",
        MmValueType.Ip => "ip",
        MmValueType.Url => "url",
        MmValueType.Email => "email",
        MmValueType.Enums => "enums",
        MmValueType.Media => "media",
        _ => "unknown",
    };

    public static MmValueType FromTypeString(string s) => s.ToLowerInvariant() switch
    {
        "doc" => MmValueType.Doc,
        "obj" => MmValueType.Obj,
        "map" => MmValueType.Map,
        "vec" => MmValueType.Vec,
        "arr" => MmValueType.Arr,
        "bool" => MmValueType.Bool,
        "i" => MmValueType.I,
        "i8" => MmValueType.I8,
        "i16" => MmValueType.I16,
        "i32" => MmValueType.I32,
        "i64" => MmValueType.I64,
        "u" => MmValueType.U,
        "u8" => MmValueType.U8,
        "u16" => MmValueType.U16,
        "u32" => MmValueType.U32,
        "u64" => MmValueType.U64,
        "bigint" => MmValueType.BigInt,
        "f32" => MmValueType.F32,
        "f64" => MmValueType.F64,
        "decimal" => MmValueType.Decimal,
        "str" => MmValueType.Str,
        "bytes" => MmValueType.Bytes,
        "datetime" => MmValueType.DateTime,
        "date" => MmValueType.Date,
        "time" => MmValueType.Time,
        "uuid" => MmValueType.Uuid,
        "ip" => MmValueType.Ip,
        "url" => MmValueType.Url,
        "email" => MmValueType.Email,
        "enums" => MmValueType.Enums,
        "media" => MmValueType.Media,
        _ => MmValueType.Unknown,
    };
}
